# Generated by Django 4.1.2 on 2023-01-09 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0008_direct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direct',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterField(
            model_name='direct',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='متن پیام'),
        ),
        migrations.AlterField(
            model_name='direct',
            name='view',
            field=models.BooleanField(default=False, verbose_name='پیام دیده شده؟'),
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com1', to=settings.AUTH_USER_MODEL, verbose_name='کاربر اول')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com2', to=settings.AUTH_USER_MODEL, verbose_name='کاربر دوم')),
            ],
        ),
        migrations.AddField(
            model_name='direct',
            name='communication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='account.communication', verbose_name='ارتباط'),
        ),
    ]
