# Generated by Django 4.1.2 on 2023-01-09 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_direct_options_alter_direct_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direct',
            name='communication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='account.communication', verbose_name='ارتباط'),
        ),
    ]
