# Generated by Django 4.1.2 on 2023-01-09 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_direct_communication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direct',
            name='receiver',
        ),
    ]
